# ================================
# System
server:
  port: 8001
  
  
# ================================
# Spring
spring:
  # --------------
  # Profiles
  profiles:
    active: local
  # --------------
  # Cloud App Name
  application:
    name: jonastalk-chat-api
  # --------------
  # MVC
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # For Swagger
    static-locations: /resources/**
    view:
      prefix: /WEB-INF/chat/
      suffix: .jsp
  # --------------
  # Server Auto Restart
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  
# ================================
# Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8999/eureka
  
  
# ================================ 
# Logging
logging:
  file:
    path: ./logs
    name: jonastalk-chat-api.log
    max-history: 30
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line - %line] - %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method - %line] - %msg%n"
    rolling-file-name: "./logs/jonastalk-chat-api.%d{yyyy-MM-dd}.%i"


# ================================
# Feign Client
jonastalk-auth-api:
  ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 3000


# ================================
# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : k/hUpdMKgvyR4Hf+Sv4SRQ== # Encrypted in AES-256


# ================================
# WebSocket 
ws:
  redis:
    prefix:
      common: "jonastalk-chat-api::ws::"
      chat: "chat::"
    #key:
      #chat:
        #value:
          #session: session
  chat:
    ttl-mins: 5